config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :price_per_night, numericality: true
  validates :number_of_guests, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]
  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @flat.update(flat_params)
    redirect_to flats_path(@flat)
  end

  def destroy
    @flat.delete
    redirect_to flats_path
  end


  private

  def flat_params
    # => Whitelisting
    params.require(:flat).permit(:name, :address, :description, :number_of_guests, :price_per_night)
  end

  def set_flat
    @flat = Flat.find(params[:id].to_i)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :number_of_guests %>
  <%= f.input :price_per_night %>

  <%= f.submit "Add a flat", class: "btn btn-primary" %>
<% end %>

app/views/flats/edit.html.erb
<h1>Edit a Flat</h1>

<%= render 'form', restaurant: @flat %>

app/views/flats/index.html.erb
<div class="container">
  <h1>All our flats (<%= @flats.length %>)</h1>

  <div class="flats">
    <ul>
      <% @flats.each do |flat| %>
      <li class="card-p" style="width: 18rem;">
        <div class="text-flat">
          <h3 class="card-title"><%= flat.name %></h3>
          <p class="card-text"><%=  flat.address %></p>
          <p>👨‍👩‍👧‍👦: <%= flat.number_of_guests %></p>
          <p>💶: <%= flat.price_per_night %></p>
        </div>

        <div class="nums">
          <div class="more"> <p> <%= link_to "More Info",  flat_path(flat) %> </p> </div>
          <div class="edit"> <p><%= link_to "Edit",  edit_flat_path(flat)%></p></div>
          <div class="delete">
          <p><%= link_to "Delete",  flat_path(flat), method: :delete %></div></p>
        </div>

        <% end %>


      </li>

    </ul>
  </div>

</div>

app/views/flats/show.html.erb
<div class="container">

  <div class="title">
    <h1><%= @flat.name %></h1>
    <p><%= @flat.address %></p>
  </div>

  <div class="description">

    <h3>A bit more about this flat...</h3>
    <p><%= @flat.description %></p>
  </div>

  <div class="details">
    <p>👨‍👩‍👧‍👦: <%= @flat.number_of_guests %></p>
    <p>💶: <%= @flat.price_per_night %></p>

  </div>





</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <div class="navbar navbar-light bg-light">
      <h2>Airbnb</h2>

      <div>
        <%= link_to "All flats",  flats_path%>
        <%= link_to "Add a new flat",  new_flat_path%>
      </div>


    </div>
    <%= yield %>
  </body>
</html>